Improved responsive design, toolbar & some fixes
Joolmo/adminSite pull request #10
Opened 2020-04-24 09:25 UTC by Joolmo

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/moneyCardSection/index.scss
> +                span::before {
es scss el before se puede meter dentro del span de la linea 22 &:before

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/moneyCardSection/index.scss
> +                span.selected {
lo mismo que el before, dentro del span &.selected

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/moneyCardSection/index.scss
> +@media (min-width: 700px) {
las sizes que utilices en mediaqueries es buena practica ponerlas como variables en el fichero de variables.scss asi si te toca reajustar solo reajustas una $tablet-size = 700px y aqui utilizas la variable

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/moneyCardSection/index.scss
> +        &:nth-child(1) div:nth-child(2) button.layoutButton {
He visto a lo largo del codigo mucho nth-child, esta bien pero ten en cuenta que si alguien llega a querer modificar es un poco mareo cuando hay muchos. no lo cambies pero tenlo en cuenta para mas adelante y sustituir alguno por una clase

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/moneyCardSection/index.tsx
> +    AllCoinsService({start: 50, limit: 56, musts: ["XRP", "XEM", "ETH", "BTC"]})
las variables que se utilizan para configurar llamadas, si son constantes siempre define una const arriba y usala aqui, start, must y limit deberian ser constantes fuera del componente

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/moneyCardSection/index.tsx
> +  const moveHeadband = (direction: directions) => {
bien por usar un enum pero no te hace falta, podrias utilizar un boolean y checkear solo una variable, esto te mejoraria los condicionales, lo vemos

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/moneyCardSection/index.tsx
> +          <Palette src={`https://cors-anywhere.herokuapp.com/${image}`} key={index}>
lo de los index como key

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/navItem/index.scss
>      &.unToggled > .nav-list { max-height: 0px; }
no me parece que sea necesario, mañana me explicas donde se usa y miramos

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/newsCard/index.scss
> +            -webkit-box-orient: vertical;
no se que hace esto, me lo cuentas dema como curiosidad

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/newsCard/index.scss
> +@media (min-width: 450px) {
sizes en variables

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/newsCard/index.tsx
>          if(newsDate.getDate() === actualDate.getDate() && newsDate.getMonth() === actualDate.getMonth()) {
miramos mañana optimizacion de condicionales

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/newsSection/index.tsx
> +                    { news.slice(0,4).map((news, index) => <NewsCard key={index} news={news}/>) }
lo de los indices

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/toolbar/index.scss
> +@media (min-width: 860px) {
sizes en variables

2020-04-24 14:18 UTC, Franpastoragusti commented on src/services/allCoinsService.tsx
> +export const AllCoinsService = async ({start = 0, limit, musts}:  IProps): Promise<ICoin[]> => {
no me gusta el nombre mañana me explicas y vemos a ver

2020-04-24 14:18 UTC, Franpastoragusti commented on src/services/allCoinsService.tsx
> +    const path = "all/coinlist"
las constantes arriba

2020-04-24 14:18 UTC, Franpastoragusti commented on src/services/newsFeedService.tsx
> +    const path = "v2/news/"
constantes arriba

2020-04-24 14:18 UTC, Franpastoragusti commented on src/app.scss
> +@media (min-width: 900px){
sizes en variables

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/graphicCard/index.scss
> +@media (min-width: 700px) {
sizes en variables

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/graphicCard/index.tsx
> +                            { coins.map((item, index) => <li key={index} onClick={() => {
no uses index como key, solo a la desesperada, en otro comment te lo explico por ahi

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/header/index.tsx
> +        return items.map((item, index) => {
lo de los indices

2020-04-24 14:18 UTC, Franpastoragusti commented on src/components/lastestActivities/index.scss
> +@media (min-width: 700px) {
sizes en variables

2020-04-26 20:07 UTC, Joolmo commented on src/components/lastestActivities/index.tsx
> +                        { coins.map((coin, index) => <button key={index} className={!index ? "selected" : undefined}>{coin}</button>) }
solved

2020-04-26 20:07 UTC, Joolmo commented on src/components/lastestActivities/index.tsx
> +                            <li className={className} key={index}>
solved

2020-04-26 20:07 UTC, Joolmo commented on src/components/moneyCardSection/index.scss
> +                span::before {
solved

2020-04-26 20:07 UTC, Joolmo commented on src/components/moneyCardSection/index.scss
> +                span.selected {
solved

2020-04-26 20:07 UTC, Joolmo commented on src/components/moneyCardSection/index.scss
> +@media (min-width: 700px) {
solved

2020-04-26 20:08 UTC, Joolmo commented on src/app.scss
> +@media (min-width: 900px){
solved

2020-04-26 20:08 UTC, Joolmo commented on src/components/graphicCard/index.scss
> +@media (min-width: 700px) {
solved

2020-04-26 20:08 UTC, Joolmo commented on src/components/graphicCard/index.tsx
> +                            { coins.map((item, index) => <li key={index} onClick={() => {
solved

2020-04-26 20:08 UTC, Joolmo commented on src/components/header/index.tsx
> +        return items.map((item, index) => {
solved

2020-04-26 20:09 UTC, Joolmo commented on src/components/lastestActivities/index.scss
> +@media (min-width: 700px) {
solved

2020-04-27 08:15 UTC, Franpastoragusti requested changes
src/components/moneyCardSection/index.tsx
src/components/newsSection/index.tsx

2020-04-27 08:15 UTC, Franpastoragusti commented on src/components/moneyCardSection/index.tsx
> +    if(direction === directions.left) {
if(!isRight && 0 < scrollable.scrollLeft) {
       scrollable.scroll(scrollable.scrollLeft - widthCard, 0)
return 
}
      if( 0 < scrollable.scrollWidth - (scrollable.scrollLeft + section.offsetWidth)) { 
        scrollable.scroll(scrollable.scrollLeft + widthCard, 0)
      }

2020-04-27 08:44 UTC, Franpastoragusti approved these changes

2020-04-27 08:44 UTC, merged